name: VipCommand
author: Apple3910
api: [1.14.0, 2.0.0]
version: 1.0
main: Example\\Main

command:
VIP:
description: information VIP
usage: /vip
SVIP:
description: information SuperVIP
usage: /svip
UVIP:
description: information UltraVIP
YT:
description: information YouTube
usage: /youtube
