# VIP INFO
vipinfo: §C[==========§eVIP§c==========]
Info:

# SUPERVIP INFO
svipinfo: §C[==========§eSVIP§c==========]
Info:
# ULTRAVIP INFO
uvipinfos: §C[==========§UVIP§c==========]
Info:
# YOUTUBE INFO
ytinfo: §C[==========§cYou§fTube§c==========]
Info:
