# VIP INFO
vipinfo: §C[==========§eVIP§c==========]
Info:

# SUPERVIP INFO
svipinfo: §C[==========§eSVIP§c==========]
Info:

# ULTRAVIP INFO
uvipinfo: §C[==========§UVIP§c==========]
Info:

# YOUTUBE INFO
ytinfo: §C[==========§4You§fTube§c==========]
Info:
